### ISSUE TITLE
Flapping behavior on issue management

### ISSUE THREAD

**Issue by alevick** [chuckSMASH/pong#3]
There seems to be some bug causing the status of other issues to flap between open and closed. See https://github.com/chuckSMASH/pong/issues/2 as an example.

Unable to identify bug in software. Bug potentially exists in wetware of project manager.

**Comment by chucksmash** [comment]
Issue is with upstream dependency. Closed WONTFIX.

**Comment by alevick** [comment]
lol... wtf is an upstream dependency of your brain?

**Comment by chucksmash** [comment]
Maintainer's brain is upstream of this repo. See relevant requirements.txt entry. Please resubmit as bug against proper project.
